FROM nginx:alpine

# Remove default nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx configuration
COPY proxy/nginx.conf /etc/nginx/conf.d/

COPY src/static /app/static

# Ensure static files are readable
RUN chmod -R 755 /app/static

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
